config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'groups#index'

  resources :users, only: [:edit, :update]
  resources :groups, only: [:new, :edit, :create, :update] do
    resources :messages
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  validates :name, presence: true
  has_many :users, through: :memberships
  has_many :memberships
  has_many :messages
end

app/models/membership.rb
class Membership < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/message.rb
class Message < ApplicationRecord
  validates :text, presence: true, if: -> { image.blank? }
  validates :image, presence: true, if: -> { text.blank? }
  belongs_to :user
  belongs_to :group

  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :groups, through: :memberships
  has_many :memberships
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
      devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

  def after_sign_out_path_for(resource)
   new_user_session_path
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :find_group, only: [:edit, :update]

  def index
    @message = Message.new
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to root_path, notice: 'グループを作成しました'
    else
      render :new, alert: 'グループ作成に失敗しました'
    end
  end

  def edit
  end

  def update
    if @group.update(group_params)
      redirect_to root_path, notice: 'グループが編集されました'
    else
      render :edit
    end
  end

  private
  def group_params
    params.require(:group).permit(:name, {user_ids: []})
  end

  private
  def find_group
    @group = Group.find(params[:id])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @group = Group.find(params[:group_id])
    @message = Message.new
  end

  def create
    @message = Message.new(create_message)
    if @message.save
      redirect_to group_messages_path, notice: 'メッセージを投稿しました'
    else
      redirect_to :back, alert: 'メッセージを入力してください'
    end

  end

  private
  def create_message
    params.require(:message).permit(:text, :image).merge(user_id: current_user.id, group_id: params[:group_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
    @user = current_user
  end

  def update
    if current_user.update(profile_params)
      redirect_to :root
    else
      render :edit
    end
  end

  private
  def profile_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
  def message_if(group)
    if group.messages.blank?
      "まだメッセージはありません。"
    else
      latest = group.messages.order("created_at DESC")[0]
       if latest.text.blank?
         "画像が投稿されています"
       else
        latest.text
      end
    end
  end
end

app/views/group/index.html.haml
!!!
%html
%body
  .notification
    .notice
      = render 'layouts/flash'
      = yield

  .chat
    .chat-side-bar
      .chat-side-bar__header
        .chat-side-bar__header__contents
          .chat-side-bar__header__contents__name takao toriyama
          %li.chat-side-bar__header__contents__new-group
            = link_to new_group_path do
              %i.fa.fa-pencil-square-o.icon
          %li.chat-side-bar__header__contents__edit
            = link_to edit_user_path(current_user) do
              %i.fa.fa-cog.icon
      .chat-side-bar__groups
        .chat-side-bar__groups-lists
          .chat-side-bar__group name

    .chat-main
      .chat-main__header
        .chat-main__header__group.clearfix
          .chat-main__header__group-name Test
          .chat-main__header__group-edit
            = link_to 'edit', edit_group_path(Group.first)
        .chat-main__header__members
          %li.member Member: Toriyama Takao
      .chat-main__body
        .chat-main__body__messages
          .chat-main__body__messages__1
            .chat-main__body__messages__1-name toriyama takao
            .chat-main__body__messages__1-time 2017/09/05 20:52:52
            .chat-main__body__messages__1-body hoge
      .chat-main__footer
        %form#new_message.chat-main__footer-form
          %input{name: "utf8", type: "hidden", value: "✓"}/
          %input{name: "authenticity_token", type: "hidden", value: "P6CIHc51pIrfwCn8ZlizaLL+7+4t6EQx3q3aDIGfMN9rtSC47VH8kJZJEVnHJPMUgjuBWewie17QFo/UtKEAyg=="}/
          .chat-main__footer-body
            %input#message_body.message{name: "message[body]", placeholder: "type a message", type: "text"}/
            %label.chat-file{for: "message_image"}
              %input#message_image.image{name: "message[image]", type: "file"}/
              %i.fa.fa-image
            %input.submit{"data-disable-with": "Send", name: "commit", type: "submit", value: "Send"}/

app/views/group/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  = form_for @group do |f|
    .chat-group-form__errors
      %h2
        1件のエラーが発生しました。
        %ul
          %li エラーです
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        %label.chat-group-form__label{:for => "chat_group_name"} グループ名
      .chat-group-form__field--right
        = f.text_field :name, class: "chat-group-form__input", placeholder: "グループ名を入力してください"
    .chat-group-form__field.clearfix
      / この部分はインクリメンタルサーチ（ユーザー追加の非同期化のときに使用します
      /
        <div class='chat-group-form__field--left'>
        <label class="chat-group-form__label" for="chat_group_チャットメンバーを追加">チャットメンバーを追加</label>
        </div>
        <div class='chat-group-form__field--right'>
        <div class='chat-group-form__search clearfix'>
        <input class='chat-group-form__input' id='user-search-field' placeholder='追加したいユーザー名を入力してください' type='text'>
        </div>
        <div id='user-search-result'></div>
        </div>
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        %label.chat-group-form__label{:for => "chat_group_チャットメンバー"} チャットメンバー
      .chat-group-form__field--right
        .check_box
          = collection_check_boxes(:users, :user_ids, User.all, :id, :name) do |b|
            = b.label { b.check_box + b.text }
        / グループ作成機能の追加時はここにcollection_check_boxesの記述を入れてください
        / この部分はインクリメンタルサーチ（ユーザー追加の非同期化のときに使用します
        /
          <div id='chat-group-users'>
          <div class='chat-group-user clearfix' id='chat-group-user-22'>
          <input name='chat_group[user_ids][]' type='hidden' value='22'>
          <p class='chat-group-user__name'>seo_kyohei</p>
          </div>
          </div>
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
      .chat-group-form__field--right
        = f.submit "Save", name: "commit", class: "chat-group-form__action-btn"

app/views/groups/_side-bar.html.haml
.chat-side-bar
  .chat-side-bar__header
    .chat-side-bar__header__contents
      .chat-side-bar__header__contents__name takao toriyama
      %li.chat-side-bar__header__contents__new-group
        = link_to new_group_path do
          %i.fa.fa-pencil-square-o.icon
      %li.chat-side-bar__header__contents__edit
        = link_to edit_user_path(current_user) do
          %i.fa.fa-cog.icon
  .chat-side-bar__groups
    .chat-side-bar__groups-lists
      .chat-side-bar__group
        .chat-side-bar__group-name
          - current_user.groups.each do |group|
            = link_to group_messages_path(group.id) do
              .chat-side-bar__group-name
                = group.name
                .chat-side-bar__group-message
                  = message_if(group)

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  = form_for @group do |f|
    -if @group.errors.any?
      .chat-group-form__errors
        %h2
          #{@group.errors.count} 件のエラーが発生しました。
          %ul
            - @group.errors.full_messages.each do |msg|
              %li
                #{msg}
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        %label.chat-group-form__label{:for => "chat_group_name"} グループ名
      .chat-group-form__field--right
        = f.text_field :name, class: "chat-group-form__input", placeholder: "グループ名を入力してください"
    .chat-group-form__field.clearfix
      / この部分はインクリメンタルサーチ（ユーザー追加の非同期化のときに使用します
      /
        <div class='chat-group-form__field--left'>
        <label class="chat-group-form__label" for="chat_group_チャットメンバーを追加">チャットメンバーを追加</label>
        </div>
        <div class='chat-group-form__field--right'>
        <div class='chat-group-form__search clearfix'>
        <input class='chat-group-form__input' id='user-search-field' placeholder='追加したいユーザー名を入力してください' type='text'>
        </div>
        <div id='user-search-result'></div>
        </div>
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        %label.chat-group-form__label{:for => "chat_group_チャットメンバー"} チャットメンバー
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
      .chat-group-form__field--right
        / グループ作成機能の追加時はここにcollection_check_boxesの記述を入れてください
        .check_box
          = collection_check_boxes(:group, :user_ids, User.all, :id, :name) do |b|
            = b.label { b.check_box + b.text }
        = f.submit "Save", name: "commit", class: "chat-group-form__action-btn"

app/views/groups/index.html.haml
.notification
  .notice
    = render 'layouts/flash'
    = yield

.chat
  = render partial: "side-bar", locals: {group: @group}

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  = form_for @group do |f|
    -if @group.errors.any?
      .chat-group-form__errors
        %h2
          #{@group.errors.count} 件のエラーが発生しました。
          %ul
            - @group.errors.full_messages.each do |msg|
              %li
                #{msg}
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        %label.chat-group-form__label{:for => "chat_group_name"} グループ名
      .chat-group-form__field--right
        = f.text_field :name, class: "chat-group-form__input", placeholder: "グループ名を入力してください"
    .chat-group-form__field.clearfix
      / この部分はインクリメンタルサーチ（ユーザー追加の非同期化のときに使用します
      /
        <div class='chat-group-form__field--left'>
        <label class="chat-group-form__label" for="chat_group_チャットメンバーを追加">チャットメンバーを追加</label>
        </div>
        <div class='chat-group-form__field--right'>
        <div class='chat-group-form__search clearfix'>
        <input class='chat-group-form__input' id='user-search-field' placeholder='追加したいユーザー名を入力してください' type='text'>
        </div>
        <div id='user-search-result'></div>
        </div>
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        %label.chat-group-form__label{for: "chat_group_チャットメンバー"} チャットメンバー
      .chat-group-form__field--right
        .check_box
          = collection_check_boxes(:group, :user_ids, User.all, :id, :name) do |b|
            = b.label { b.check_box + b.text }
        / グループ作成機能の追加時はここにcollection_check_boxesの記述を入れてください
        / この部分はインクリメンタルサーチ（ユーザー追加の非同期化のときに使用します
        /
          <div id='chat-group-users'>
          <div class='chat-group-user clearfix' id='chat-group-user-22'>
          <input name='chat_group[user_ids][]' type='hidden' value='22'>
          <p class='chat-group-user__name'>seo_kyohei</p>
          </div>
          </div>
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
      .chat-group-form__field--right
        = f.submit "Save", name: "commit", class: "chat-group-form__action-btn"

app/views/layouts/_flash.html.haml
- flash.each do |key, value|
  = content_tag(:div, value, class: "flash flash__#{key}")

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ChatSpace
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/messages/index.html.haml
.notification
  .notice
    = render 'layouts/flash'
    = yield

.chat
  = render partial: "groups/side-bar"
  .chat-main
    .chat-main__header
      .chat-main__header__group.clearfix
        .chat-main__header__group-name
          =  @group.name
        .chat-main__header__group-edit
          = link_to 'Edit', edit_group_path(current_user)
      .chat-main__header__members
        %li.member 
          = "Member:"
          - @group.memberships.each do |m|
            #{m.user.name}
    .chat-main__body
      .chat-main__body__messages
        - @group.messages.each do |message|
          .chat-main__body__message
            .chat-main__body__message__name
              = current_user.name
            .chat-main__body__message__time
              = message.created_at
            .chat-main__body__message__body
              = message.text
    .chat-main__footer
      .chat-main__footer-form
      = form_for [@group, @message] do |f|
        .chat-main__footer-body
          = f.text_field :text, class: "message", placeholder:"type a message"
          %label.chat-file
            = f.file_field :image, class: 'image'
            %i.fa.fa-picture-o
          = f.submit "Send", class: 'submit'

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for @user do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'